---
- name: Testing andrewrothstein.synopsysctl
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'synopsysctl --version'
      ansible.builtin.command: /usr/local/bin/synopsysctl --version
      changed_when: false
      register: synopsysctl_test_output
    - name: Output of 'synopsysctl --version'
      ansible.builtin.debug:
        msg: '{{ synopsysctl_test_output.stdout }}'
