---
- hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - command: /usr/local/bin/synopsysctl --version
      register: synopsysctl_test_output
    - name: synopsysctl --version
      debug:
        msg: '{{ synopsysctl_test_output.stdout }}'
