---
- name: resolve platform specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: check for install in {{ synopsysctl_install_dir }}
  become: true
  stat:
    path: '{{ synopsysctl_install_dir }}'
  changed_when: false
  register: synopsysctl_binary
- when: not synopsysctl_binary.stat.exists
  block:
    - name: downloading {{ synopsysctl_url }} to {{ synopsysctl_tmp_archive }}
      become: true
      become_user: root
      get_url:
        url: '{{ synopsysctl_url }}'
        dest: '{{ synopsysctl_tmp_archive }}'
        mode: 0644
        checksum: '{{ synopsysctl_checksum }}'
    - name: mkdir {{ synopsysctl_install_dir }}
      become: true
      become_user: root
      file:
        path: '{{ synopsysctl_install_dir }}'
        mode: 0755
        state: directory
    - name: unarchiving {{ synopsysctl_tmp_archive }} into {{ synopsysctl_install_dir }}
      become: true
      become_user: root
      unarchive:
        remote_src: true
        src: '{{ synopsysctl_tmp_archive }}'
        dest: '{{ synopsysctl_install_dir }}'
        creates: '{{ synopsysctl_exe }}'
  always:
    - name: rm {{ synopsysctl_tmp_archive }}
      become: true
      become_user: root
      file:
        path: '{{ synopsysctl_tmp_archive }}'
        state: absent
- name: linking {{ synopsysctl_link }} to {{ synopsysctl_exe }}
  become: true
  become_user: root
  file:
    src: '{{ synopsysctl_exe }}'
    dest: '{{ synopsysctl_link }}'
    state: link
