---
- name: Installing andrewrothstein.unarchivedeps
  ansible.builtin.include_role:
    name: andrewrothstein.unarchivedeps
- name: Resolve platform specific vars
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: Check for install in {{ synopsysctl_install_dir }}
  become: true
  ansible.builtin.stat:
    path: '{{ synopsysctl_install_dir }}'
  changed_when: false
  register: synopsysctl_binary
- name: Downloading synopsysctl
  when: not synopsysctl_binary.stat.exists
  block:
    - name: Downloading {{ synopsysctl_url }} to {{ synopsysctl_tmp_archive }}
      become: true
      become_user: root
      ansible.builtin.get_url:
        url: '{{ synopsysctl_url }}'
        dest: '{{ synopsysctl_tmp_archive }}'
        mode: '644'
        checksum: '{{ synopsysctl_checksum }}'
    - name: Mkdir {{ synopsysctl_install_dir }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ synopsysctl_install_dir }}'
        mode: '755'
        state: directory
    - name: Unarchiving {{ synopsysctl_tmp_archive }} into {{ synopsysctl_install_dir }}
      become: true
      become_user: root
      ansible.builtin.unarchive:
        remote_src: true
        src: '{{ synopsysctl_tmp_archive }}'
        dest: '{{ synopsysctl_install_dir }}'
        creates: '{{ synopsysctl_exe }}'
  always:
    - name: Rm {{ synopsysctl_tmp_archive }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ synopsysctl_tmp_archive }}'
        state: absent
- name: Linking {{ synopsysctl_link }} to {{ synopsysctl_exe }}
  become: true
  become_user: root
  ansible.builtin.file:
    src: '{{ synopsysctl_exe }}'
    dest: '{{ synopsysctl_link }}'
    state: link
